# Disable some built-in rules
config:
  no-trailing-spaces: false

# Fix any fixable errors
fix: true

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

# Define glob expressions to ignore
ignores:
  - "CHANGELOG.md"
  - "./taget/"

# Disable banner message on stdout (only valid at root)
noBanner: true

# Disable progress on stdout (only valid at root)
noProgress: true

# Use a specific formatter (only valid at root)
outputFormatters:
  - - markdownlint-cli2-formatter-default

# Show found files on stdout (only valid at root)
showFound: true
