# https://embarkstudios.github.io/cargo-deny/

[graph]
# cargo-deny is really only ever intended to run on the "normal" tier-1 targets
targets = [
  "aarch64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "aarch64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]
all-features = true

[output]
feature-depth = 1

[advisories]
version = 2
ignore = [
  #"RUSTSEC-0000-0000",
  #{ id = "RUSTSEC-0000-0000", reason = "you can specify a reason the advisory is ignored" },
  #"a-crate-that-is-yanked@0.1.1", # you can also ignore yanked crate versions if you wish
  #{ crate = "a-crate-that-is-yanked@0.1.1", reason = "you can specify why you are ignoring the yanked crate" },
]

[bans]
multiple-versions = "deny"
wildcards = 'deny'
deny = [
  { crate = "git2", use-instead = "gix" },
  { crate = "openssl", use-instead = "rustls" },
  { crate = "openssl-sys", use-instead = "rustls" },
  { crate = "cmake", use-instead = "cc" },
]
skip = []
skip-tree = []

# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = ["Apache-2.0", "MIT"]
exceptions = [
  # Use exceptions for these as they only have a single user
  { allow = ["Zlib"], crate = "tinyvec" },
  { allow = ["Unicode-DFS-2016"], crate = "unicode-ident" },
  { allow = ["OpenSSL"], crate = "ring" },
]
