name: Commitlint

on:
  push:
    branches-ignore:
      - "release-plz*"
  pull_request:
    branches-ignore:
      - "release-plz*"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    steps:
      - name: Run commitlint
        uses: opensource-nepal/commitlint@v1
